security:
    # Gestion des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username  # à adapter si tu n'utilises pas l'email comme identifiant
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)

    # Pare-feux (firewalls)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            # custom_authenticator: App\Security\AppAuthenticator

            logout:
                path: app_logout
                target: '/'

        
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: admin


            remember_me: 
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # Contrôle d'accès
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
